# Profil par défaut - Autorisations environnementales
schema_version: 2
id: autorisations_environnementales
label: "Autorisations environnementales"
out_subdir: bilan_autorisations_environnementales

filter:
  type: keywords
  keywords: ["autorisation environnementale", "autorisations environnementales"]
  columns: [theme, type_actio, nom_dossie]

natinf_pve: []
natinf_pej: []

analyse_PVe: true

sources:
  point_ctrl: true
  pej: true
  pa: true
  pve: true

periode_analyse:
  ventilation:
    type: auto
    seuil_jours: 366

options:
  cartes:
    label: "Intégration des cartes"
    default: true
    ask: false
