# Profil par défaut - Autres gestion qualitative
schema_version: 2
id: autres_gestion_qualitative
label: "Autres actions liées à la gestion qualitative"
out_subdir: bilan_autres_gestion_qualitative

filter:
  type: keywords
  keywords: ["gestion qualitative"]
  columns: [theme, type_actio, nom_dossie]

natinf_pve: []
natinf_pej: []

analyse_PVe: true

sources:
  point_ctrl: true
  pej: true
  pa: true
  pve: true

periode_analyse:
  ventilation:
    type: auto
    seuil_jours: 366

options:
  cartes:
    label: "Intégration des cartes"
    default: true
    ask: false
