schema_version: 2
id: tub
label: "Agrainage en Zone TUB"
title_label: "Zone TUB"
out_subdir: bilan_tub
restrict_geo: tub

filter:
  type: tub

natinf_pej: ["27742", "25001"]
natinf_pve: ["27742", "25001"]

analyse_PVe: true

_map_id: tub

presentation:
  sections:
    titles:
      sec22: "2.2. Répartition de l'activité par thèmes (contrôles + PEJ)"
  blocks:
    sec22:
      group_by: theme

cartographie:
  pochoir: zone_a_risque
  emprise: zone_a_risque
  cartes_actives:
    - domaines
    - resultats
    - procedures
  couches_vecteurs_extra:
    - zone_tub
