schema_version: 2
id: types_usager_cible
label: Bilan types d'usagers – ciblé
out_subdir: bilan_types_usager_cible
filter:
  type: type_usager
  type_usager_target: []
analyse_PVe: false
sources:
  point_ctrl: true
  pej: true
  pa: true
  pve: false
periode_analyse:
  ventilation:
    type: auto
    seuil_jours: 366
analyses:
  type_usager: true
options:
  cartes:
    label: Intégration des cartes
    default: true
    ask: true
