coordination_departement:
  # Préfixes d'intégration des noms de départements (ex: Département "du" Doubs)
  "Doubs": "du"
  "Jura": "du"
  "Haute-Saône": "de la"
  "Saône-et-Loire": "de"
  "Yonne": "de l'"
  "Territoire de Belfort": "du"
  "Nièvre": "de la"
  "Côte-d'Or": "de la"
  "Côte d'Or": "de la"
  "Ain": "de l'"
  "Ardèche": "de l'"
  "Drôme": "de la"
  "Isère": "de l'"
  "Loire": "de la"
  "Rhône": "du"
  "Savoie": "de la"
  "Haute-Savoie": "de la"
  "Allier": "de l'"
  "Cantal": "du"
  "Haute-Loire": "de la"
  "Puy-de-Dôme": "du"
  "Aisne": "de l'"
  "Nord": "du"
  "Oise": "de l'"
  "Pas-de-Calais": "du"
  "Somme": "de la"
  "Cher": "du"
  "Eure-et-Loir": "d'"
  "Indre": "de l'"
  "Indre-et-Loire": "d'"
  "Loir-et-Cher": "de"
  "Loiret": "du"
  "Aube": "de l'"
  "Marne": "de la"
  "Haute-Marne": "de la"
  "Ardennes": "des"
  "Meurthe-et-Moselle": "de"
  "Meuse": "de la"
  "Moselle": "de la"
  "Bas-Rhin": "du"
  "Haut-Rhin": "du"
  "Vosges": "des"
  "Corse-du-Sud": "de la"
  "Haute-Corse": "de la"
  "Guadeloupe": "de la"
  "Martinique": "de la"
  "Guyane": "de la"
  "La Réunion": "de la"
  "Mayotte": "de"
