"""
Configuration des cartes pour les bilans agrainage / chasse-agrainage.
Généré par les outils de configuration (GUI ou mode interactif).

Les dates de période doivent correspondre à celles des scripts d'analyse :
- agrainage : analyse_agrainage.py (DATE_DEB, DATE_FIN)
- chasse : analyse_chasse_agrainage.py (ou analyse_chasse.py) — thématique chasse uniquement
"""

from typing import Dict

from config_cartes_model import (
    GeometryMode,
    FilterType,
    RendererType,
    ClassificationMode,
    OutputFormat,
    LayerSymbologyConfig,
    ProfileConfig,
    OutputConfig,
    BasemapConfig,
    GlobalConfig,
)


DEFAULT_PROFILES: Dict[str, ProfileConfig] = {
    'agrainage': ProfileConfig(
        id='agrainage',
        title="Bilan agrainage 2025-2026 — Agrainage illicite (NATINF 27742) — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_agrainage.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            "Zone d'interdiction d'agrainage": LayerSymbologyConfig(
        layer_name="Zone d'interdiction d'agrainage",
        legend_label="Zone d'interdiction d'agrainage",
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'Zone infectée': LayerSymbologyConfig(
        layer_name='Zone infectée',
        legend_label='Zone infectée',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'Zone à risque': LayerSymbologyConfig(
        layer_name='Zone à risque',
        legend_label='Zone à risque',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label='localisation_infrac_FAITS_20260205',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='pochoir_sd21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20251231_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20251231_wgs84',
        legend_label='point_ctrl_20251231_wgs84',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='point_ctrl_20260205_wgs84',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'pve_agrainage_points_centroides': LayerSymbologyConfig(
        layer_name='pve_agrainage_points_centroides',
        legend_label='pve_agrainage_points_centroides',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
        },
        title_main='',
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'chasse': ProfileConfig(
        id='chasse',
        title="Bilan chasse 2025-2026 — Chasse — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_chasse.png',
        date_deb='2025-09-01',
        date_fin='2026-03-01',
        layers={
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label='localisation_infrac_FAITS_20260205',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='pochoir_sd21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20251231_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20251231_wgs84',
        legend_label='point_ctrl_20251231_wgs84',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='point_ctrl_20260205_wgs84',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
        },
        title_main='Bilan activité de contrôle chasse',
        subtitle='2025 2026',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'piegeage': ProfileConfig(
        id='piegeage',
        title="Bilan piégeage — Contrôles piégeage — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_piegeage.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label='Infractions PJ',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20251231_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20251231_wgs84',
        legend_label='Contrôles piégeage',
        filter_type='point_ctrl_piegeage',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Oranges',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles piégeage',
        filter_type='point_ctrl_piegeage',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Oranges',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles piégeage — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global': ProfileConfig(
        id='global',
        title="Bilan global — Contrôles et procédures — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles (localisations, département)',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='#003A76',
        symbol_size_mm=1.9,
        symbol_shape='circle'
    ),
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label="Procédure d'enquête judiciaire",
        filter_type='pj',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Oranges',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles et procédures — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global_procedures': ProfileConfig(
        id='global_procedures',
        title="Bilan global SD21 — Procédures — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global_procedures.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
                layer_name='pochoir_sd21',
                legend_label='Périmètre SD21',
                filter_type='',
                geometry_mode='polygon_fill',
                renderer_type='graduated',
                field='',
                classification_mode='quantile',
                num_classes=5,
                palette='Blues',
                symbol_size_mm=2.0,
                symbol_shape='circle'
            ),
            'localisation_infrac': LayerSymbologyConfig(
                layer_name='localisation_infrac',
                layer_role='pej',
                legend_label="Procédure d'enquête judiciaire",
                filter_type='pj',
                geometry_mode='polygon_fill',
                renderer_type='graduated',
                field='',
                classification_mode='quantile',
                num_classes=5,
                palette='Oranges',
                symbol_size_mm=2.0,
                symbol_shape='circle'
            ),
        },
        title_main="Procédures judiciaires — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global_usagers': ProfileConfig(
        id='global_usagers',
        title="Bilan global SD21 — Contrôles par types d’usagers — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global_usagers.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles (types d’usagers)',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='categorized',
        field='CASE\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%Particulier%\' THEN \'Particulier\'\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%Agriculteur%\' THEN \'Agriculteur\'\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%Collectiv%\' THEN \'Collectivité\'\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%Entreprise%\' THEN \'Entreprise\'\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%sylvic%\' THEN \'Acteurs sylvicoles\'\n  WHEN attribute(@feature, \'type_usager\') ILIKE \'%Autre%\' THEN \'Autre\'\n  ELSE \'Autre\'\nEND\n',
        classification_mode='quantile',
        num_classes=5,
        palette='#003A76,#53AB60,#F4A261,#E76F51,#90BF83,#4296CE',
        symbol_size_mm=1.9,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles — types d’usagers — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'procedures_pve': ProfileConfig(
        id='procedures_pve',
        title="Bilan procédures judiciaires et PVe — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_procedures_pve.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label="Procédure d'enquête judiciaire",
        filter_type='pj',
        geometry_mode='polygon_fill',
        renderer_type='single',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'communes_france': LayerSymbologyConfig(
        layer_name='communes_france',
        legend_label='Procès verbal électronique',
        filter_type='',
        symbology_source='yaml',
        geometry_mode='polygon_centroid',
        renderer_type='single',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Oranges',
        color_rgb=(255, 128, 0),
        symbol_size_mm=3.0,
        symbol_shape='triangle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='single',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=1.5,
        symbol_shape='circle'
    ),
        },
        title_main="Procédures judiciaires et PVe — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global_usagers_agriculteurs': ProfileConfig(
        id='global_usagers_agriculteurs',
        title="Bilan SD21 — Contrôles agriculteurs — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global_usagers_agriculteurs.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles agriculteurs',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='categorized',
        field='CASE\n  WHEN "type_usager" ILIKE \'%Agriculteur%\' THEN \'Agriculteur et autres acteurs agricoles\'\n  ELSE NULL\nEND\n',
        classification_mode='quantile',
        num_classes=5,
        palette='#53AB60',
        symbol_size_mm=1.9,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles — agriculteurs — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global_resultats': ProfileConfig(
        id='global_resultats',
        title="Bilan SD21 — Résultats des contrôles — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global_resultats.png',
        date_deb='2025-01-01',
        date_fin='2025-12-31',
        layers={
            'localisation_infrac_FAITS_20260205': LayerSymbologyConfig(
        layer_name='localisation_infrac_FAITS_20260205',
        legend_label='localisation_infrac_FAITS_20260205',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        color_rgb=(31, 120, 180),
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='pochoir_sd21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl': LayerSymbologyConfig(
        layer_name='point_ctrl',
        layer_role='point_controles',
        legend_label='Résultats des contrôles',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='categorized',
        field='coalesce(attribute(@feature, \'resultat\'), attribute(@feature, \'Resultat\'), attribute(@feature, \'resultat_controle\'), \'Non renseigné\')',
        classification_mode='quantile',
        num_classes=5,
        palette='#53AB60,#E76F51,#F4A261,#003A76',
        color_rgb=(31, 120, 180),
        symbol_size_mm=1.5,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles — résultats — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'global_domaines': ProfileConfig(
        id='global_domaines',
        title="Bilan global — Contrôles par domaines — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_global_domaines.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles par domaine',
        filter_type='point_ctrl_global',
        geometry_mode='polygon_fill',
        renderer_type='categorized',
        field='coalesce(attribute(@feature, \'domaine\'), \'Hors domaine\')',
        classification_mode='quantile',
        num_classes=5,
        palette='#003A76,#53AB60,#F4A261,#E76F51,#90BF83,#4296CE,#264653,#2A9D8F',
        symbol_size_mm=1.9,
        symbol_shape='circle'
    ),
        },
        title_main="Contrôles par domaines — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
    'toutes': ProfileConfig(
        id='toutes',
        title="Bilan global — Toutes les cartes — Côte-d'Or",
        layout_name="modele_mise_en_page_carto_bilans",
        output_filename='carte_toutes.png',
        date_deb='2025-01-01',
        date_fin='2026-02-05',
        layers={
            'pochoir_sd21': LayerSymbologyConfig(
        layer_name='pochoir_sd21',
        legend_label='Périmètre SD21',
        filter_type='',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
            'point_ctrl_20260205_wgs84': LayerSymbologyConfig(
        layer_name='point_ctrl_20260205_wgs84',
        legend_label='Contrôles chasse',
        filter_type='point_ctrl_chasse',
        geometry_mode='polygon_fill',
        renderer_type='graduated',
        field='',
        classification_mode='quantile',
        num_classes=5,
        palette='Blues',
        symbol_size_mm=2.0,
        symbol_shape='circle'
    ),
        },
        title_main="Bilan global — Toutes les cartes — Côte-d'Or",
        subtitle='',
        layout_title_item_id='titre_principal',
        layout_subtitle_item_id='sous_titre',
    ),
}


# Configuration globale par défaut
CONFIG = GlobalConfig(
    project_qgis_path='',
    kit_ofb_path='',
    output_dir='',
    basemap=BasemapConfig(enabled=True),
    output=OutputConfig(format='png', dpi=150, page_size='A4', orientation='landscape'),
    profiles=DEFAULT_PROFILES.copy(),
)
